version: '3.8'

services:
  chat_genus:
    container_name: chat-data
    image: node:lts
    environment:
      - CHAT_ENV=DEVELOP
    working_dir: '/home/proyects/nameproyect'
    command: sh -c "npm install && npm run build"
    tty: true
    volumes:
      - ./:/home/proyects/nameproyect
      - /home/proyects/nameproyect/node_modules
    privileged: true